### ISSUE TITLE
Issues with position: fixed; in CSS(again)

### ISSUE THREAD

**Issue by GGorAA** [bobboteck/JoyStick#12]
Hello again. I've seen last update of joystick that added support for `position: absolute;` and `position: fixed;` CSS attributes. I downloaded the latest version, extracted joy.js to my HTML folder, and... nothing. Still doesn't work. If you need, here is the repo (site is in `HTML` folder): https://github.com/GGorAA/GLaDOS.

How to fix this issue?

**Comment by bobboteck** [comment]
Hi @GGorAA, now I understand your situation.
As I wrote to you, JoyStick now supports Fixed or Absolute positioning via CSS, but this style must be applied directly to the DIV that contains JoyStick. In your case, the CSS positioning property is assigned to a DIV, but it is a parent of the DIV that contains the JoyStick, to function correctly in your case, you should also give a fixed positioning to the DIVs that have the IDs "bodyJoy" and "headJoy", that was the ID of DIV that contains the JoySticks in your project.
I hope I was clear.

P.S. You have same picture of a project? It looks interesting.

**Comment by GGorAA** [comment]
Thanks for the advice!

P.S. What picture? I don't understand your request

**Comment by bobboteck** [comment]
> P.S. What picture? I don't understand your request

Picture, images of your project, I read that was a Raspberry PI, same mobile part, ecc...
If you want I can add it in the [Use case](https://github.com/bobboteck/JoyStick/wiki/UseCases) page of Wiki.

I can close the Issue now?

**Comment by GGorAA** [comment]
Yes, you can close.
And can we move our conversation to a messenger, Telegram for example?

**Comment by bobboteck** [comment]
You can find me on telegram as @bobboteck
