### ISSUE TITLE
The joystick does not move to the left (moves to the right) after I add position: fixed; top: 0; to the CSS grid div CSS (HTML provided)

### ISSUE THREAD

**Issue by artisticfox8** [bobboteck/JoyStick#26]
Hello, I want to use your library for a mobile site. The layout is however for some reason a bit taller than the view port in the landscape orientation and full screen mode. So I want to disable scrolling with `position: fixed; top: 0;` That however produces the following result: the joystick can't be moved left and is moved right when I move my mouse to the left.
```
<html>
<head>
<meta charset="utf-8">

<script type="text/javascript" src="joy.js"></script>
<style type="text/css">

	.wrapper {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    grid-template-rows: 200px 200px;
    grid-gap: 20px;
	}
	.joy3Posizione{
		display: none;
	}
	.popisek{
		font-family: Helvetica;padding-top:9px;font-weight: 600;
	}
    .c{
    	background-color: grey;
    }
    th, td {
	  padding-left:5px;padding-right: 5px
	}

   .plyn {
   	transform: rotate(-90deg);
	  -webkit-appearance: none;
	  width: 100%;
	  height: 25px;
	  background: #d3d3d3;
	  outline: none;
	  opacity: 0.7;
	  -webkit-transition: .2s;
	  transition: opacity .2s;
	  tran: 0px;
	}

	.plyn:hover {
	  opacity: 1;
	}

	.plyn::-webkit-slider-thumb {
	  -webkit-appearance: none;
	  appearance: none;
	  width: 25px;
	  height: 25px;
	  background: #04AA6D;
	  cursor: pointer;
	}

	.plyn::-moz-range-thumb {
	  width: 25px;
	  height: 25px;
	  background: #04AA6D;
	  cursor: pointer;
	}
	.wrapper{
	    position: fixed;
        top: 0;
	}
	#IP{
		width: 230px;
	}
	#confirm{
	    width: 60px;
	}
</style>
</head>
<body>

<div class="wrapper">
	<!-- Example of FIXED or ABSOLUTE position -->
	<div class="c" id="containe"> <!-- style="width:200px;height:200px"> -->
		<div style="display: inline"> <!-- style="position:fixed;bottom:125px;left:750px;" -->

		<input class="joy3Posizione" type="text"> <!-- to tam musí být -->
		<input class="joy3Posizione" type="text">
		Y :<input class="t" id="joy3Y" type="text">
	    <p class="popisek">text</p>
		</div>
		<div style="width:200px;height:200px;display: block;margin: 0 auto;">
			 <input type="range" min="1" max="100" value="50" class="plyn">
		</div>
	</div>
	<div class="c">
		<center class="popisek">text:
		<table style="font-family: Helvetica;">
		<tr>
		    <th>text</th>
		    <th>text</th> 
		  </tr>
			<tr>
		    <td>text</td>
		    <td>100%</td>
			</tr>
			<tr>
		    <td>text</td>
		    <td>100%</td>
			</tr>
		</table>
			<input type="button" value="Pause" id="siesta">
		  <input type="button" value="Action" id="Action">
		</center>
	</div>
    
    <div class="c" id="containe"> <!-- style="width:200px;height:200px" -->
		<div style="display: inline"> <!-- style="position:fixed;bottom:125px;left:750px;" -->

		<input class="joy3Posizione" type="text"> <!-- to tam musí být -->
		<input class="joy3Posizione" type="text">
		X :<input id="joy4X" class="t" type="text"><br>
		Y :<input id="joy4Y" class="t" type="text">
	    <center class="popisek">text</center>
		</div>
		<div id='container' style="width:200px;height:200px;display: block;margin: 0 auto;"></div>
	</div>

	<div style="padding-top: 100px">
	 IP: <input  id="IP" type="text"> <input type="button" id="confirm" value="OK">
         <input type="button" id="clear" value="Clear">
	 
	 <input id="IP_default" type="button" value="Výchozí">
	 <p id="received data">
	  <p id="adress">
	</div>
</div>
<script type="text/javascript">

	var joy3 = new JoyStick('container'); //směr

	var joy3X = document.getElementById("joy4X");
	var joy3Y = document.getElementById("joy4Y");
	var joy4Y = document.getElementById("joy3Y"); //

	//document.getElementByClassName("plyn")[0];
  document.getElementById("IP_default").addEventListener("click",function(e){
  	document.getElementById("IP").value = "http://127.0.0.1:8000/";
  	 sendTo = "http://127.0.0.1:8000/";
  });
  
  document.getElementById("confirm").addEventListener("click",function(e){
      sendTo = document.getElementById("IP").value;
  });

	document.getElementById("clear").addEventListener("click",function(e){
	      document.getElementById("IP_default").click();
	      document.getElementById("IP").value = "";
				document.documentElement.requestFullscreen();
				screen.orientation.lock("landscape");
});
</script>
<!-- <script type="text/javascript" src="posilac.js"></script> -->
</body>
</html>
```

**Comment by artisticfox8** [comment]
> Hello, I want to use your library for a mobile site. The layout is however for some reason a bit taller than the view port in the landscape orientation and full screen mode. So I want to disable scrolling with `position: fixed; top: 0;` That however produces the following result: the joystick can't be moved left and is moved right when I move my mouse to the left.
> 
> ```
> <html>
> <head>
> <meta charset="utf-8">
> 
> <script type="text/javascript" src="joy.js"></script>
> <style type="text/css">
> 
> 	.wrapper {
>     display: grid;
>     grid-template-columns: 1fr 1fr 1fr;
>     grid-template-rows: 200px 200px;
>     grid-gap: 20px;
> 	}
> 	.joy3Posizione{
> 		display: none;
> 	}
> 	.popisek{
> 		font-family: Helvetica;padding-top:9px;font-weight: 600;
> 	}
>     .c{
>     	background-color: grey;
>     }
>     th, td {
> 	  padding-left:5px;padding-right: 5px
> 	}
> 
>    .plyn {
>    	transform: rotate(-90deg);
> 	  -webkit-appearance: none;
> 	  width: 100%;
> 	  height: 25px;
> 	  background: #d3d3d3;
> 	  outline: none;
> 	  opacity: 0.7;
> 	  -webkit-transition: .2s;
> 	  transition: opacity .2s;
> 	  tran: 0px;
> 	}
> 
> 	.plyn:hover {
> 	  opacity: 1;
> 	}
> 
> 	.plyn::-webkit-slider-thumb {
> 	  -webkit-appearance: none;
> 	  appearance: none;
> 	  width: 25px;
> 	  height: 25px;
> 	  background: #04AA6D;
> 	  cursor: pointer;
> 	}
> 
> 	.plyn::-moz-range-thumb {
> 	  width: 25px;
> 	  height: 25px;
> 	  background: #04AA6D;
> 	  cursor: pointer;
> 	}
> 	.wrapper{
> 	    position: fixed;
>         top: 0;
> 	}
> 	#IP{
> 		width: 230px;
> 	}
> 	#confirm{
> 	    width: 60px;
> 	}
> </style>
> </head>
> <body>
> 
> <div class="wrapper">
> 	
> 	<div class="c" id="containe"> 
> 		<div style="display: inline"> 
> 
> 		<input class="joy3Posizione" type="text"> 
> 		<input class="joy3Posizione" type="text">
> 		Y :<input class="t" id="joy3Y" type="text">
> 	    <p class="popisek">text</p>
> 		</div>
> 		<div style="width:200px;height:200px;display: block;margin: 0 auto;">
> 			 <input type="range" min="1" max="100" value="50" class="plyn">
> 		</div>
> 	</div>
> 	<div class="c">
> 		<center class="popisek">text:
> 		<table style="font-family: Helvetica;">
> 		<tr>
> 		    <th>text</th>
> 		    <th>text</th> 
> 		  </tr>
> 			<tr>
> 		    <td>text</td>
> 		    <td>100%</td>
> 			</tr>
> 			<tr>
> 		    <td>text</td>
> 		    <td>100%</td>
> 			</tr>
> 		</table>
> 			<input type="button" value="Pause" id="siesta">
> 		  <input type="button" value="Action" id="Action">
> 		</center>
> 	</div>
>     
>     <div class="c" id="containe"> 
> 		<div style="display: inline"> 
> 
> 		<input class="joy3Posizione" type="text"> 
> 		<input class="joy3Posizione" type="text">
> 		X :<input id="joy4X" class="t" type="text"><br>
> 		Y :<input id="joy4Y" class="t" type="text">
> 	    <center class="popisek">text</center>
> 		</div>
> 		<div id='container' style="width:200px;height:200px;display: block;margin: 0 auto;"></div>
> 	</div>
> 
> 	<div style="padding-top: 100px">
> 	 IP: <input  id="IP" type="text"> <input type="button" id="confirm" value="OK">
>          <input type="button" id="clear" value="Clear">
> 	 
> 	 <input id="IP_default" type="button" value="Výchozí">
> 	 <p id="received data">
> 	  <p id="adress">
> 	</div>
> </div>
> <script type="text/javascript">
> 
> 	var joy3 = new JoyStick('container'); //směr
> 
> 	var joy3X = document.getElementById("joy4X");
> 	var joy3Y = document.getElementById("joy4Y");
> 	var joy4Y = document.getElementById("joy3Y"); //
> 
> 	//document.getElementByClassName("plyn")[0];
>   document.getElementById("IP_default").addEventListener("click",function(e){
>   	document.getElementById("IP").value = "http://127.0.0.1:8000/";
>   	 sendTo = "http://127.0.0.1:8000/";
>   });
>   
>   document.getElementById("confirm").addEventListener("click",function(e){
>       sendTo = document.getElementById("IP").value;
>   });
> 
> 	document.getElementById("clear").addEventListener("click",function(e){
> 	      document.getElementById("IP_default").click();
> 	      document.getElementById("IP").value = "";
> 				document.documentElement.requestFullscreen();
> 				screen.orientation.lock("landscape");
> });
> </script>
> 
> </body>
> </html>
> ```

When the position is not fixed, it works well.

**Comment by lafkpages** [comment]
Same

**Comment by bobboteck** [comment]
Sorry for very late response, I have tested your code and as I wrote [here](https://github.com/bobboteck/JoyStick/issues/12#issuecomment-642448355) for the issue #12 you simply need to add `position:fixed;` in the style of div that contain the JoyStick.
This does not affect the positioning of the other objects, but it allows the JoyStick to function properly.

I report only the line affected by the change, which was previously:
`<div id='container' style="width:200px;height:200px;display: block;margin: 0 auto;"></div>`
to work properly it must be:
`<div id='container' style="position:fixed;width:200px;height:200px;display: block;margin: 0 auto;"></div>`

@lafkpages I suppose your problem is similar, so you can apply the same solution.

**Comment by lafkpages** [comment]
Ok, it works. But it doesn't work if you put, for example, a div inside another div, and put the joystick in the inner div. And the outer div has `position: fixed;`

**Comment by bobboteck** [comment]
Hello @lafkpages from what you write it seems to me the same situation as @artisticfox8.
If I can, I suggest you to move the question to the [Discussions](https://github.com/bobboteck/JoyStick/discussions) section of the repository, and to report your code or at least an example of this in order to evaluate the situation.
