### ISSUE TITLE
Every time I move the Joystick on Chrome on Android I get joy.js:163 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

### ISSUE THREAD

**Issue by artisticfox8** [bobboteck/JoyStick#27]
```
joy.js:163 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
onTouchMove @ joy.js:163
```
This happens every time I move the joystick.
![Snímek obrazovky 2021-10-16 130644](https://user-images.githubusercontent.com/77014769/137584922-4aaa3df5-2f27-490b-9bb2-916548124461.png)

**Comment by artisticfox8** [comment]
This is from the USB Chrome Devtools. To launch the file on Android on localhost:8000 I use the Termux app and the `python3 -m http.server `command

**Comment by artisticfox8** [comment]
@bobboteck Will you merge this fix?

**Comment by bobboteck** [comment]
Thanks for the suggestion, the patch was now implemented
