### ISSUE TITLE
Not size=200px

### ISSUE THREAD

**Issue by takeru** [bobboteck/JoyStick#8]
https://jsfiddle.net/ssktkr/6gLtoryh/

Changed width/height 190px.
GetX,Y is returns -111 ... 111

**Comment by bobboteck** [comment]
Hi @takeru the problem you encountered has been solved with FIX at #9. If you download the latest version of the file joy.js or joy.min.js you should no longer have the problem.
For now I have not created a new release.
Let me know if you solved it!

**Comment by bobboteck** [comment]
Hi @takeru, I wait same other days, after if don't receive any feedback, I consider it closed.

**Comment by bobboteck** [comment]
Sorry, I close it, because for me it is a duplicate of an Issue already managed, and because I have not received any further feedback
